### ISSUE TITLE
any chance of uploading the produced files?

### ISSUE THREAD

**Issue by fommil** [Supersagee/AiSeasonCreator#1]
Thanks for this, it looks like something that I would be very interested in using.

Would it be possible to upload the output of running this... or are the files just too big? Even a couple of headline series like IMSA and GT3, would be awesome.

**Comment by fommil** [comment]
This is so easy to use, there is no need for having the files pre-prepared, and now I can create whatever I want. Thanks again!

**Comment by Supersagee** [comment]
@fommil Sorry I was slow on my response. Yes, I’ve created the app in a way that makes it super simple to setup seasons. Hope you can enjoy it!
