### ISSUE TITLE
Sim fails to load after deleting Track from AI Season

### ISSUE THREAD

**Issue by ChaseIngersol** [Supersagee/AiSeasonCreator#6]
* Create an AI Season (settings used pictured below)
* Click the AI Season in iRacing and go to `Manage Season > Edit`
* Go to the `Tracks` section and remove one of them from the season, then click `Save`

The Weather section then endlessly displays it's "loading" state: 
![image](https://github.com/Supersagee/AiSeasonCreator/assets/49707385/7088152a-57e3-4b6a-987d-3eba5f15bb2b)

And clicking `Continue > Race` leads to the following error:
![image](https://github.com/Supersagee/AiSeasonCreator/assets/49707385/46c6820a-42d1-46f2-a327-92ab4e216722)

Settings used while creating AI Season:
![image](https://github.com/Supersagee/AiSeasonCreator/assets/49707385/6621eea0-324e-430e-88fd-cbbbc70e0fab)

---

If I have some time in the near future, I'll investigate and try to fix this. 

And thanks for all the hard work you've put into this tool, it's very much appreciated! 👍

---

## Update:

For anyone else running into the same issue, selecting the `Select Tracks` option while creating the season will let you remove the unwanted track during creation of the season, which solves the issue for me.

**Comment by Supersagee** [comment]
Hello! Yes, this continues to be an issue, and I'm not sure on a way to completely resolve is. As a work around, when editing a schedule, going to each individual event, clicking on Weather, and then clicking Regenerate will properly set the weather.
